# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69d5056e9278ae64764917735b54aa761f29d7bbdb7a98ded4f663056b4aec5a17f9f31778b6a59c70f460fb423de0ce3ab8bcc93dbdccd6ec40707b092bafe2

test:
  secret_key_base: 09c35d6739ac08523ddfcd07d2a22775a3e5acfc2a8fa96014037f02e611f906a4c45ecf8f32e7ea6ce004ef6660576e1410a53fe6d2275b4b286c23e876ffe7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
